language: node_js
node_js:
- '10'
cache:
- npm
script:
- echo "skipping tests"
before_deploy:
- npm install -g firebase-tools
deploy:
  provider: script
  script: firebase deploy --project bibiphelp --token $FB_TOKEN