language: node_js
node_js:
- '10'
cache:
- npm
script:
- echo "skipping tests"
before_deploy:
- npm install -g firebase-tools
- cd ./functions && npm install && npm run build && cd ..
deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --only database,functions --project bibiphelp --token $FB_TOKEN --force