language: node_js
node_js:
- '10'
cache:
- npm
script:
- echo "skipping tests"
before_deploy:
- npm install -g firebase-tools
- cd ./functions && npm install && npm run build && cd ..
deploy:
  provider: script
  script: firebase deploy --token $FB_TOKEN
env:
  global:
    secure: TKGing8AtYfV54vKDtGeWNil8dT7nmPb0AfngjX3RguWFl9Zb3jXbLTlPLnI8PVXZGieN9gHaWHUmg6BafwzTsQeqV7awZrmW3QKh+7d/Co/1Zx9WFp5niLs2hfWylUcvR7np/SCn355BphnoMYVqQdUq92BcaHhktYPgAWPGpnpHW/cHJCsrEIknpogPxSwmc9yeEVh6C5OKkqE7bfIK1s1EYZQWgKHUWmAyXPvGBShodam83u9s3Gd9BYCcPU25x1UPK8TJw9m2M7W3i6udMp3AO5FqXWnKg/ZtDNMYJY4I172q02EZXBsRRVJq5Kb0a/I7n41nhAamAiAT+iOhO2mz7u5c3svTOwhv97x4mMNQs+2kDu5Hi9q/+lIVwiyWNcIYTNqOQLldT3Jn2s1LZIkc6+bMRl8bi1JeKdgY1uFRvYbincYunujg9lofZz5f6qfpCFiP7CbZRMY5Ob03XpqYg2cXCMWKLyYpT07hZ7us2xdAtYbaYsFf8mTE7HIfBylr89FCIfPU5fRuJktGrst9HaVSgo1USzKmYB1/+ZuL0Dt1CCrQ5srx/MfwxQpPjMboR3eTwEu0XjQxQVysxGtDy/HzHiRBlVNcEJ/e7YKf8dPR7Enrzp18cW8Nqw4vaF0gPR10cSfIWc9RydF7gXS4Nh5Tvt22qHiNqo8Lq8=
